In [1]:
import pandas as pd
df=pd.read_csv(r'/home/nineleaps/Downloads/03_pos_transactions.csv')
df.head()

     tx_id     tx_date             amount currency  qty payment_method
0  TX-1000  2025-02-03             £94.04      INR    1            UPI
1  TX-1001  2024-04-22         INR 170.29      USD    1           Cash
2  TX-1002  2023-07-06             £56.51      eur    1           Card
3  TX-1003  2025-03-18             €66.04      GBP    1           Card
4  TX-1004  12/11/2023  224.4751214459086      EUR    1           Cash

In [2]:
df.dtypes

tx_id               str
tx_date             str
amount              str
currency            str
qty               int64
payment_method      str
dtype: object

In [3]:
df.isnull().sum()

tx_id             0
tx_date           0
amount            0
currency          0
qty               0
payment_method    0
dtype: int64

In [4]:
df.head()

     tx_id     tx_date             amount currency  qty payment_method
0  TX-1000  2025-02-03             £94.04      INR    1            UPI
1  TX-1001  2024-04-22         INR 170.29      USD    1           Cash
2  TX-1002  2023-07-06             £56.51      eur    1           Card
3  TX-1003  2025-03-18             €66.04      GBP    1           Card
4  TX-1004  12/11/2023  224.4751214459086      EUR    1           Cash

In [5]:
df['tx_date']=pd.to_datetime(df['tx_date'],format='mixed')

In [6]:
df.head()

     tx_id    tx_date             amount currency  qty payment_method
0  TX-1000 2025-02-03             £94.04      INR    1            UPI
1  TX-1001 2024-04-22         INR 170.29      USD    1           Cash
2  TX-1002 2023-07-06             £56.51      eur    1           Card
3  TX-1003 2025-03-18             €66.04      GBP    1           Card
4  TX-1004 2023-12-11  224.4751214459086      EUR    1           Cash

In [7]:
df['amount']=df['amount'].replace(r'[^0-9.]',"",regex=True)

In [8]:
df.head()

     tx_id    tx_date             amount currency  qty payment_method
0  TX-1000 2025-02-03              94.04      INR    1            UPI
1  TX-1001 2024-04-22             170.29      USD    1           Cash
2  TX-1002 2023-07-06              56.51      eur    1           Card
3  TX-1003 2025-03-18              66.04      GBP    1           Card
4  TX-1004 2023-12-11  224.4751214459086      EUR    1           Cash

In [19]:
df['currency']=df['currency'].replace({'eur':'EUR','usd':'USD'})

In [20]:
df['currency'].value_counts()

currency
USD    292
EUR    268
GBP    155
INR    133
Name: count, dtype: int64

In [22]:
df.head(20)
df['qty']=df['qty'].apply(lambda x:-x if x<0 else x)

In [23]:
df.head(20)

      tx_id    tx_date              amount currency  qty payment_method
0   TX-1000 2025-02-03               94.04      INR    1            UPI
1   TX-1001 2024-04-22              170.29      USD    1           Cash
2   TX-1002 2023-07-06               56.51      EUR    1           Card
3   TX-1003 2025-03-18               66.04      GBP    1           Card
4   TX-1004 2023-12-11   224.4751214459086      EUR    1           Cash
5   TX-1005 2024-01-24               54.22      USD    1         Wallet
6   TX-1006 2023-08-20               82.57      EUR    1            UPI
7   TX-1007 2024-12-15               80.10      INR    3            UPI
8   TX-1008 2023-12-24  249.02052284536433      EUR    1           card
9   TX-1009 2024-01-30              161.85      EUR    2            UPI
10  TX-1010 2024-10-23   63.02664035046225      USD    3            UPI
11  TX-1011 2023-03-04               78.21      INR    1           Cash
12  TX-1012 2024-06-13              143.09      USD    1            UPI
13  TX-1013 2024-07-31              197.83      INR    1           Cash
14  TX-1014 2024-10-06              260.93      EUR    2         Wallet
15  TX-1015 2023-12-09              194.72      EUR    1            UPI
16  TX-1016 2023-06-16              164.49      GBP    3         Wallet
17  TX-1017 2024-08-30              219.56      EUR    1            UPI
18  TX-1018 2024-09-07              145.28      INR    1           Card
19  TX-1019 2025-02-20              126.87      USD    2           card

In [26]:
df=df.drop_duplicates()
df.head(10)

     tx_id    tx_date              amount currency  qty payment_method
0  TX-1000 2025-02-03               94.04      INR    1            UPI
1  TX-1001 2024-04-22              170.29      USD    1           Cash
2  TX-1002 2023-07-06               56.51      EUR    1           Card
3  TX-1003 2025-03-18               66.04      GBP    1           Card
4  TX-1004 2023-12-11   224.4751214459086      EUR    1           Cash
5  TX-1005 2024-01-24               54.22      USD    1         Wallet
6  TX-1006 2023-08-20               82.57      EUR    1            UPI
7  TX-1007 2024-12-15               80.10      INR    3            UPI
8  TX-1008 2023-12-24  249.02052284536433      EUR    1           card
9  TX-1009 2024-01-30              161.85      EUR    2            UPI

In [29]:
df.dtypes

tx_id                        str
tx_date           datetime64[us]
amount                   float64
currency                     str
qty                        int64
payment_method               str
dtype: object

In [28]:
df['amount']=pd.to_numeric(df['amount'])

In [31]:
df.head(20)

      tx_id    tx_date      amount currency  qty payment_method
0   TX-1000 2025-02-03   94.040000      INR    1            UPI
1   TX-1001 2024-04-22  170.290000      USD    1           Cash
2   TX-1002 2023-07-06   56.510000      EUR    1           Card
3   TX-1003 2025-03-18   66.040000      GBP    1           Card
4   TX-1004 2023-12-11  224.475121      EUR    1           Cash
5   TX-1005 2024-01-24   54.220000      USD    1         Wallet
6   TX-1006 2023-08-20   82.570000      EUR    1            UPI
7   TX-1007 2024-12-15   80.100000      INR    3            UPI
8   TX-1008 2023-12-24  249.020523      EUR    1           card
9   TX-1009 2024-01-30  161.850000      EUR    2            UPI
10  TX-1010 2024-10-23   63.026640      USD    3            UPI
11  TX-1011 2023-03-04   78.210000      INR    1           Cash
12  TX-1012 2024-06-13  143.090000      USD    1            UPI
13  TX-1013 2024-07-31  197.830000      INR    1           Cash
14  TX-1014 2024-10-06  260.930000      EUR    2         Wallet
15  TX-1015 2023-12-09  194.720000      EUR    1            UPI
16  TX-1016 2023-06-16  164.490000      GBP    3         Wallet
17  TX-1017 2024-08-30  219.560000      EUR    1            UPI
18  TX-1018 2024-09-07  145.280000      INR    1           Card
19  TX-1019 2025-02-20  126.870000      USD    2           card

In [33]:
df.to_csv(r'/home/nineleaps/Downloads/ETL_Mock_Cleaned.csv')